name: Production flow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Setup dependencies
        run: pnpm i
      - name: Type check
        run: pnpm typechecking
      - name: Unit test
        run: pnpm test
      - name: Build
        run: pnpm build:production
      - name: Deploy
        uses: D3rHase/rsync-deploy-action@latest
        with:
          REPOSITORY_PATH: dist/
          USER: vlad805
          HOST: '135.181.147.70'
          SERVER_PATH: /home/vlad805/projects/radio/
          PRIVATE_SSH_KEY: ${{ secrets.ssh_key }}
