name: Production flow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup SSH key
        run: set -eu && mkdir "$HOME/.ssh" && echo "${{ secrets.ssh_key }}" > "$HOME/.ssh/key" && chmod 600 "$HOME/.ssh/key"
      - name: Setup dependencies
        run: npm ci
      - name: Type check
        run: npm run typechecking
      - name: Unit test
        run: npm run test
      - name: Build
        run: npm run build:production
      - name: Deploy
        run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress . vlad805@135.181.147.70:/home/vlad805/projects/radio/
